default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: care_helper_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: care_helper_test

production:
  <<: *default
  adapter: postgresql
  password: <%= ENV['CARE_HELPER_DATABASE_PASSWORD'] %>
